code --install-extension 2gua.rainbow-brackets
code --install-extension dbaeumer.vscode-eslint
code --install-extension dracula-theme.theme-dracula
code --install-extension eamodio.gitlens
code --install-extension jpoissonnier.vscode-styled-components
code --install-extension naumovs.color-highlight
code --install-extension oderwat.indent-rainbow
code --install-extension PKief.material-icon-theme
code --install-extension ritwickdey.LiveServer
code --install-extension rocketseat.rocketseatreactjs
code --install-extension steoates.autoimport
code --install-extension HookyQR.beautify
code --install-extension ecmel.vscode-html-css
code --install-extension usernamehw.errorlens
code --install-extension formulahendry.auto-close-tag
code --install-extension formulahendry.auto-rename-tag
code --install-extension editorconfig.editorconfig
code --install-extension esbenp.prettier-vscode
code --install-extension chenglou92.rescript-vscode
code --install-extension arcticicestudio.nord-visual-studio-code
