[appearance]

[appearance.themes]
system_theme = false
theme = "adeberry"

[appearance.vertical_tabs]
enabled = true

[appearance.icon]
app_icon = "comets"

[appearance.text]
notebook_font_size = 14.0
font_size = 13.0

[appearance.window]
zoom_level = 110

[general]
default_session_mode = "agent"
show_warning_before_quitting = false

[agents]

[agents.third_party]
should_render_cli_agent_toolbar = true

[agents.third_party.cli_agent_toolbar_enabled_commands]
coo = "Codex"
coosp = "Codex"
opc = "OpenCode"
pi = "Pi"

[agents.warp_agent]
is_any_ai_enabled = true

[agents.warp_agent.other]
show_agent_notifications = true
show_conversation_history = true

[code]

[code.editor]
show_code_review_button = true
show_project_explorer = true
show_global_search = true
open_file_editor = { external_editor = "zed" }
open_code_panels_file_editor = { external_editor = "zed" }

[warp_drive]
enabled = true
